# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.stdNumericCreate <- function(reserve = 0L) {
    .Call(stdvectors_stdNumericCreate, reserve)
}

.stdNumericPushBack <- function(p, toAppend) {
    invisible(.Call(stdvectors_stdNumericPushBack, p, toAppend))
}

.stdNumericSize <- function(p) {
    .Call(stdvectors_stdNumericSize, p)
}

.stdNumericClear <- function(p) {
    invisible(.Call(stdvectors_stdNumericClear, p))
}

.stdNumericToVector <- function(p) {
    .Call(stdvectors_stdNumericToVector, p)
}

.stdNumericSubset <- function(p, indexes) {
    .Call(stdvectors_stdNumericSubset, p, indexes)
}

.stdNumericReplace <- function(p, indexes, values) {
    invisible(.Call(stdvectors_stdNumericReplace, p, indexes, values))
}

.stdNumericErase <- function(p, indexFrom, indexTo) {
    invisible(.Call(stdvectors_stdNumericErase, p, indexFrom, indexTo))
}

.stdNumericClone <- function(p) {
    .Call(stdvectors_stdNumericClone, p)
}

.stdIntegerCreate <- function(reserve = 0L) {
    .Call(stdvectors_stdIntegerCreate, reserve)
}

.stdIntegerPushBack <- function(p, toAppend) {
    invisible(.Call(stdvectors_stdIntegerPushBack, p, toAppend))
}

.stdIntegerSize <- function(p) {
    .Call(stdvectors_stdIntegerSize, p)
}

.stdIntegerClear <- function(p) {
    invisible(.Call(stdvectors_stdIntegerClear, p))
}

.stdIntegerToVector <- function(p) {
    .Call(stdvectors_stdIntegerToVector, p)
}

.stdIntegerSubset <- function(p, indexes) {
    .Call(stdvectors_stdIntegerSubset, p, indexes)
}

.stdIntegerReplace <- function(p, indexes, values) {
    invisible(.Call(stdvectors_stdIntegerReplace, p, indexes, values))
}

.stdIntegerErase <- function(p, indexFrom, indexTo) {
    invisible(.Call(stdvectors_stdIntegerErase, p, indexFrom, indexTo))
}

.stdNumericClone <- function(p) {
    .Call(stdvectors_stdIntegerClone, p)
}

.stdCharacterCreate <- function(reserve = 0L) {
    .Call(stdvectors_stdCharacterCreate, reserve)
}

.stdCharacterPushBack <- function(p, toAppend) {
    invisible(.Call(stdvectors_stdCharacterPushBack, p, toAppend))
}

.stdCharacterSize <- function(p) {
    .Call(stdvectors_stdCharacterSize, p)
}

.stdCharacterClear <- function(p) {
    invisible(.Call(stdvectors_stdCharacterClear, p))
}

.stdCharacterToVector <- function(p) {
    .Call(stdvectors_stdCharacterToVector, p)
}

.stdCharacterSubset <- function(p, indexes) {
    .Call(stdvectors_stdCharacterSubset, p, indexes)
}

.stdCharacterReplace <- function(p, indexes, values) {
    invisible(.Call(stdvectors_stdCharacterReplace, p, indexes, values))
}

.stdCharacterErase <- function(p, indexFrom, indexTo) {
    invisible(.Call(stdvectors_stdCharacterErase, p, indexFrom, indexTo))
}

.stdCharacterClone <- function(p) {
    .Call(stdvectors_stdCharacterClone, p)
}

.stdLogicalCreate <- function(reserve = 0L) {
    .Call(stdvectors_stdLogicalCreate, reserve)
}

.stdLogicalPushBack <- function(p, toAppend) {
    invisible(.Call(stdvectors_stdLogicalPushBack, p, toAppend))
}

.stdLogicalSize <- function(p) {
    .Call(stdvectors_stdLogicalSize, p)
}

.stdLogicalClear <- function(p) {
    invisible(.Call(stdvectors_stdLogicalClear, p))
}

.stdLogicalToVector <- function(p) {
    .Call(stdvectors_stdLogicalToVector, p)
}

.stdLogicalSubset <- function(p, indexes) {
    .Call(stdvectors_stdLogicalSubset, p, indexes)
}

.stdLogicalReplace <- function(p, indexes, values) {
    invisible(.Call(stdvectors_stdLogicalReplace, p, indexes, values))
}

.stdLogicalErase <- function(p, indexFrom, indexTo) {
    invisible(.Call(stdvectors_stdLogicalErase, p, indexFrom, indexTo))
}

.stdCharacterClone <- function(p) {
    .Call(stdvectors_stdLogicalClone, p)
}

.stdListCreate <- function(reserve = 0L) {
    .Call(stdvectors_stdAnyCreate, reserve)
}

.stdAnyPushBack <- function(p, toAppend) {
    invisible(.Call(stdvectors_stdAnyPushBack, p, toAppend))
}

.stdAnySize <- function(p) {
    .Call(stdvectors_stdAnySize, p)
}

.stdAnyClear <- function(p) {
    invisible(.Call(stdvectors_stdAnyClear, p))
}

.stdAnyToVector <- function(p) {
    .Call(stdvectors_stdAnyToVector, p)
}

.stdAnySubset <- function(p, indexes) {
    .Call(stdvectors_stdAnySubset, p, indexes)
}

.stdAnyReplace <- function(p, index, value) {
    invisible(.Call(stdvectors_stdAnyReplace, p, index, value))
}

.stdAnyErase <- function(p, indexFrom, indexTo) {
    invisible(.Call(stdvectors_stdAnyErase, p, indexFrom, indexTo))
}

.stdAnyClone <- function(p) {
    .Call(stdvectors_stdAnyClone, p)
}

.getTypeFromString <- function(type) {
    .Call(stdvectors_getTypeFromString, type)
}

.getStringFromType <- function(type) {
    .Call(stdvectors_getStringFromType, type)
}

stdvectorCreate <- function(type = "double", reserve = 0L) {
    .Call(stdvectors_stdvectorCreate, type, reserve)
}

stdvectorPushBack <- function(sdv, values) {
    invisible(.Call(stdvectors_stdvectorPushBack, sdv, values))
}

stdvectorSize <- function(sdv) {
    .Call(stdvectors_stdvectorSize, sdv)
}

stdvectorClear <- function(sdv) {
    invisible(.Call(stdvectors_stdvectorClear, sdv))
}

stdvectorToVector <- function(sdv) {
    .Call(stdvectors_stdvectorToVector, sdv)
}

stdvectorSubset <- function(sdv, indexes) {
    .Call(stdvectors_stdvectorSubset, sdv, indexes)
}

stdvectorReplace <- function(sdv, indexes, values) {
    invisible(.Call(stdvectors_stdvectorReplace, sdv, indexes, values))
}

stdvectorErase <- function(sdv, indexFrom, indexTo) {
    invisible(.Call(stdvectors_stdvectorErase, sdv, indexFrom, indexTo))
}

stdvectorClone <- function(sdv) {
    .Call(stdvectors_stdvectorClone, sdv)
}

